### PR TITLE
Allow changing the port in the healthcheck for the minidlna image

### PR DESCRIPTION
**Pull request by Hadatko**
Not tested but i believe this may fix healthcheck 
details: https://github.com/vladgh/docker_base_images/issues/246

### CODE REVIEW

**Comment by vladgh** [comment]
This will not work because it will try to parse an `ENV` variable when building the image. It needs to be escaped here so that it's parsed only when the container starts, with the variables passed at runtime if that's possible. I will look into how that works.

**Comment by Hadatko** [comment]
Hmm from what i readi i am not sure but answer is likely no change need be done or double $ (for compose solution i read that answer is $$)

**Comment by Hadatko** [comment]
Sure. Great that it is working straightforward.

**Comment by Hadatko** [comment]
Done

**Comment by Hadatko** [comment]
Happy to help

**Pull request merged**
